"""empty message

Revision ID: 02c28152453d
Revises: 
Create Date: 2018-03-14 09:40:51.782698

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '02c28152453d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('content', sa.TEXT(), nullable=True),
                    sa.Column('badge_img', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('badge_type', sa.INTEGER(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('last_update_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('badge_type',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('get_flag', sa.BOOLEAN(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('last_update_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('badge_user',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=True),
                    sa.Column('badge_id', sa.INTEGER(), nullable=True),
                    sa.Column('create_time', sa.INTEGER(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('contest',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('content', sa.TEXT(), nullable=True),
                    sa.Column('close_rank_flag', sa.BOOLEAN(), nullable=False),
                    sa.Column('close_rank_time', sa.INTEGER(), nullable=True),
                    sa.Column('contest_flag', sa.BOOLEAN(), nullable=False),
                    sa.Column('permission_type', sa.INTEGER(), nullable=True),
                    sa.Column('password', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('user_group_id', sa.INTEGER(), nullable=True),
                    sa.Column('start_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('last_update_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('allow_mail', sa.BOOLEAN(), nullable=False),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('contest_notice',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('content', sa.TEXT(), nullable=True),
                    sa.Column('contest_id', sa.INTEGER(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('contest_problem',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('contest_id', sa.INTEGER(), nullable=True),
                    sa.Column('problem_id', sa.INTEGER(), nullable=True),
                    sa.Column('number', sa.INTEGER(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('covery_img',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('img_name', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('hyperlink_flag', sa.BOOLEAN(), nullable=False),
                    sa.Column('article_flag', sa.BOOLEAN(), nullable=False),
                    sa.Column('hyperlink', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('file',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('content', sa.TEXT(), nullable=True),
                    sa.Column('file_img', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('file_type', sa.INTEGER(), nullable=True),
                    sa.Column('download_number', sa.INTEGER(), nullable=True),
                    sa.Column('view_number', sa.INTEGER(), nullable=True),
                    sa.Column('size', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('file_name_in', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('file_name_out', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('last_update_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('file_type',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('last_update_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('forum_note',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('subject_id', sa.INTEGER(), nullable=True),
                    sa.Column('section_id', sa.INTEGER(), nullable=True),
                    sa.Column('content', sa.TEXT(), nullable=True),
                    sa.Column('floor_number', sa.INTEGER(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('forum_section',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('content', sa.TEXT(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('last_update_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('subject_number', sa.INTEGER(), nullable=True),
                    sa.Column('note_number', sa.INTEGER(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('forum_subject',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('section_id', sa.INTEGER(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('good_flag', sa.BOOLEAN(), nullable=False),
                    sa.Column('up_flag', sa.BOOLEAN(), nullable=False),
                    sa.Column('view_number', sa.INTEGER(), nullable=True),
                    sa.Column('admire_number', sa.INTEGER(), nullable=True),
                    sa.Column('reply_number', sa.INTEGER(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('judge_server',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('hostname', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('ip', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('judger_version', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('cpu_core', sa.INTEGER(), nullable=True),
                    sa.Column('memory_usage', sa.FLOAT(), nullable=True),
                    sa.Column('cpu_usage', sa.FLOAT(), nullable=True),
                    sa.Column('last_heartbeat', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('task_number', sa.INTEGER(), nullable=True),
                    sa.Column('service_url', sa.VARCHAR(length=256), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('login_log',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('ip', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('success_flag', sa.BOOLEAN(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('mail',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('content', sa.TEXT(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('mail_user',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('mail_id', sa.INTEGER(), nullable=True),
                    sa.Column('to_user', sa.INTEGER(), nullable=True),
                    sa.Column('read_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('option',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('key', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('value', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('permission',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('content', sa.TEXT(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('permission_user',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('permission_id', sa.INTEGER(), nullable=True),
                    sa.Column('user_id', sa.INTEGER(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('problem',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('description', sa.TEXT(), nullable=True),
                    sa.Column('input', sa.TEXT(), nullable=True),
                    sa.Column('output', sa.TEXT(), nullable=True),
                    sa.Column('sample', sa.JSON(), nullable=True),
                    sa.Column('test_case_id', sa.VARCHAR(length=64), nullable=True),
                    sa.Column('test_case_score', sa.JSON(), nullable=True),
                    sa.Column('hint', sa.TEXT(), nullable=True),
                    sa.Column('languages', sa.JSON(), nullable=True),
                    sa.Column('time_limit', sa.INTEGER(), nullable=True),
                    sa.Column('memory_limit', sa.INTEGER(), nullable=True),
                    sa.Column('difficulty', sa.INTEGER(), nullable=True),
                    sa.Column('source', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('spj_flag', sa.BOOLEAN(), nullable=False),
                    sa.Column('submit_number', sa.INTEGER(), nullable=True),
                    sa.Column('accepted_number', sa.INTEGER(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('last_update_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('problem_tag',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('problem_to_tag',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('problem_id', sa.INTEGER(), nullable=True),
                    sa.Column('problem_tag_id', sa.INTEGER(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('register',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('register_type_id', sa.INTEGER(), nullable=True),
                    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('gender', sa.BOOLEAN(), nullable=True),
                    sa.Column('student_number', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('telephone', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('qq', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('ip', sa.VARCHAR(length=32), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('register_type',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('last_update_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('running_flag', sa.BOOLEAN(), nullable=False),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('sign_in',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('content', sa.TEXT(), nullable=True),
                    sa.Column('begin_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('multiple_ip_flag', sa.BOOLEAN(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('last_update_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('create_user', sa.INTEGER(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('sign_in_user',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=True),
                    sa.Column('sign_in_id', sa.INTEGER(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('ip', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('similarity',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('solution_id_new', sa.INTEGER(), nullable=True),
                    sa.Column('solution_id_old', sa.INTEGER(), nullable=True),
                    sa.Column('similarity_percent', sa.INTEGER(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('special_judge',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('problem_id', sa.INTEGER(), nullable=True),
                    sa.Column('language', sa.VARCHAR(length=16), nullable=True),
                    sa.Column('code', sa.TEXT(), nullable=True),
                    sa.Column('version', sa.VARCHAR(length=16), nullable=True),
                    sa.Column('compile_flag', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('submission',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('problem_id', sa.INTEGER(), nullable=True),
                    sa.Column('contest_id', sa.INTEGER(), nullable=True),
                    sa.Column('user_id', sa.INTEGER(), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('code', sa.TEXT(), nullable=True),
                    sa.Column('result', sa.INTEGER(), nullable=True),
                    sa.Column('info', sa.JSON(), nullable=True),
                    sa.Column('language', sa.VARCHAR(length=16), nullable=True),
                    sa.Column('code_share', sa.BOOLEAN(), nullable=False),
                    sa.Column('statistic_info', sa.JSON(), nullable=True),
                    sa.Column('ip', sa.VARCHAR(length=32), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_group',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_to_group',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=True),
                    sa.Column('user_group_id', sa.INTEGER(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('username', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('head_image', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('real_name', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('ip', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('problem_page', sa.INTEGER(), nullable=True),
                    sa.Column('submit_language', sa.INTEGER(), nullable=True),
                    sa.Column('submit_number', sa.INTEGER(), nullable=True),
                    sa.Column('accepted_number', sa.INTEGER(), nullable=True),
                    sa.Column('gender', sa.BOOLEAN(), nullable=True),
                    sa.Column('school', sa.VARCHAR(length=64), nullable=True),
                    sa.Column('telephone', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('mood', sa.VARCHAR(length=256), nullable=True),
                    sa.Column('major', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('grade', sa.INTEGER(), nullable=True),
                    sa.Column('clazz', sa.INTEGER(), nullable=True),
                    sa.Column('qq', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('student_number', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('blog', sa.VARCHAR(length=256), nullable=True),
                    sa.Column('github', sa.VARCHAR(length=256), nullable=True),
                    sa.Column('reset_password_token', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('reset_password_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('session_keys', sa.JSON(), nullable=True),
                    sa.Column('visible', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_to_group')
    op.drop_table('user_group')
    op.drop_table('submission')
    op.drop_table('special_judge')
    op.drop_table('similarity')
    op.drop_table('sign_in_user')
    op.drop_table('sign_in')
    op.drop_table('register_type')
    op.drop_table('register')
    op.drop_table('problem_to_tag')
    op.drop_table('problem_tag')
    op.drop_table('problem')
    op.drop_table('permission_user')
    op.drop_table('permission')
    op.drop_table('option')
    op.drop_table('mail_user')
    op.drop_table('mail')
    op.drop_table('login_log')
    op.drop_table('judge_server')
    op.drop_table('forum_subject')
    op.drop_table('forum_section')
    op.drop_table('forum_note')
    op.drop_table('file_type')
    op.drop_table('file')
    op.drop_table('covery_img')
    op.drop_table('contest_problem')
    op.drop_table('contest_notice')
    op.drop_table('contest')
    op.drop_table('badge_user')
    op.drop_table('badge_type')
    op.drop_table('badge')
    # ### end Alembic commands ###
